global:
  env: dev

ingress:
  enabled: true
  annotations: # {}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://api-auth.test.svc.cluster.local/api/auth/auth
    nginx.ingress.kubernetes.io/auth-method: GET
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: access-token,Accept,Content-Type,Referer,User-Agent
    nginx.ingress.kubernetes.io/auth-response-headers: sub
  hosts:
    - api.dev2.test.my
  path:
    - /api/shifts
  tls: []

ingress_docs:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: docs-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  hosts:
    - api.dev2.test.my
  path:
    - /docs/shifts
  tls: []

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::296904546231:role/api-shifts-dev