{{- if .Values.ingress_docs.enabled -}}
{{- $fullName := include "helm.fullname" . -}}
{{- $ingressPath := .Values.ingress_docs.path -}}
{{- $name := include "helm.name" . -}}
{{- $servicePortName := .Values.service.name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-docs
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress_docs.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress_docs.tls }}
  tls:
  {{- range .Values.ingress_docs.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress_docs.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range $ingressPath }}
          - path: {{ . }}
            backend:
              serviceName: {{ $name }}
              servicePort: {{ $servicePortName }}
          {{- end }}
  {{- end }}
{{- end }}
