apiVersion: v1
kind: Secret
metadata:
    name: {{ include "helm.fullname" . }}-secret
type: Opaque
data:
{{- range (.Files.Lines (printf "secrets.%s.yaml.dec" .Values.global.env))}}
  {{if .}}{{$configVar := splitn ":" 2 .}}{{$configVar._0}}: {{ $configVar._1 | trim | b64enc | quote }}{{end}}
{{- end}}
